import { expect, it } from "vitest";
import twilio from "twilio";
import { validateTwilioWebhook } from "../src/signature";
it("rejects an invalid Twilio signature", () => {
  expect(validateTwilioWebhook({ authToken: "test-token", signature: "invalid", url: "https://example.test/twilio/voice", params: { CallSid: "CA123" } })).toBe(false);
});
it("accepts a signature generated by the Twilio SDK", () => {
  const authToken = "test-token";
  const url = "https://example.test/twilio/voice";
  const params = { CallSid: "CA123" };
  const signature = twilio.getExpectedTwilioSignature(authToken, url, params);
  expect(validateTwilioWebhook({ authToken, signature, url, params })).toBe(true);
});
